services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: av5ja_discord_bot
    restart: always
    environment:
      API_URL: $API_URL
      BOT_VERSION: $BOT_VERSION
      DISCORD_APPLICATION_ID: $DISCORD_APPLICATION_ID
      DISCORD_APPLICATION_SECRET: $DISCORD_APPLICATION_SECRET
      DISCORD_GUILD_ID: $DISCORD_GUILD_ID
      NODE_ENV: $NODE_ENV
      VERSION: $VERSION
