export enum StatusCode {
  // 200, 201
  SUCCESS = 'SUCCESS',
  // 204
  USER_NOT_REGISTERED = 'USER_NOT_REGISTERED',
  // 400
  ERROR_INVALID_PARAMETERS = 'ERROR_INVALID_PARAMETERS',
  // 401
  ERROR_INVALID_GAME_WEB_TOKEN = 'ERROR_INVALID_GAME_WEB_TOKEN',
  // 403
  ERROR_OBSOLETE_VERSION = 'ERROR_OBSOLETE_VERSION',
  // 404
  ERROR_NOT_FOUND = 'ERROR_NOT_FOUND',
  // 429
  ERROR_RATE_LIMIT = 'ERROR_RATE_LIMIT',
  // 499
  ERROR_BANNED_USER = 'ERROR_BANNED_USER',
  // 500, 599
  ERROR_SERVER = 'ERROR_SERVER',
  // 503
  ERROR_SERVER_MAINTENANCE = 'ERROR_SERVER_MAINTENANCE',
  // Unknown
  ERROR_UNKNOWN_STATUS = 'ERROR_UNKNOWN_STATUS',
  // Invalid URL
  ERROR_INVALID_URL = 'ERROR_INVALID_URL'
}
